### ISSUE TITLE
Missing packages for Debian wheezy

### ISSUE THREAD

**Issue by stamster** [phalcongelist/packagecloud#16] opened 2017-06-20 11:04 UTC
### Expected and Actual Behavior

> **Installing Phalcon on a server running Debian GNU/Linux 7.11, codename Wheezy**

> Provide minimal script to reproduce the issue

Following guide on official site: https://phalconphp.com/en/download/linux

> cat phalcon_stable.list 
```
# this file was generated by packagecloud.io for
# the repository at https://packagecloud.io/phalcon/stable

deb https://packagecloud.io/phalcon/stable/debian/ wheezy main
deb-src https://packagecloud.io/phalcon/stable/debian/ wheezy main
```
Install for PHP 5.6.x
```
apt-get install php5-phalcon
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package php5-phalcon
```

Results:
https://packagecloud.io/app/phalcon/stable/search?filter=all&q=&dist=wheezy

### Details

* Phalcon version: (`none yet`)
* PHP Version: (`5.6.30`)
* Operating System:
```
Distributor ID:	Debian
Description:	Debian GNU/Linux 7.11 (wheezy)
Release:	7.11
Codename:	wheezy
```
* Installation type: installing via package manager
* Zephir version (if any): n/a
* Server: Nginx | Apache | Nginx
* Other related info (Database, table schema):

**Comment by sergeyklay** [comment] 2017-06-22 06:23
We support only jessie and stretch for now. I'm closing since this is a not a bug report and I don't want a bunch of these lying around. I'd like to add support for anything/everything at some point, but keeping the issue open doesn't help that. If anyone wants to get started, I'd love that.

**Closed by sergeyklay** 2017-06-22 06:23 UTC
Labels: Debian

**Comment by stamster** [comment] 2017-06-22 06:45
OKi, but at least than that should be noted on official sites - which specific distros are supported. And some folks are still running Wheezy as it is LTS supported. And Phalcon should respect LTS distributions out there IMO.
I'll try to get started with this if I grab some spare time.
