### ISSUE TITLE
Build for Ubuntu 17.04

### ISSUE THREAD

**Issue by mayel** [phalcongelist/packagecloud#15] opened 2017-06-07 16:28 UTC
I run Ubuntu 17.04 on a dev machine and would like Phalcon packages

**Comment by sergeyklay** [comment] 2017-06-08 13:29
Cc: @virgofx

**Comment by sergeyklay** [comment] 2017-06-22 06:24
We don't support Ubuntu 17.04 for now. I'm closing since this is a not a bug report and I don't want a bunch of these lying around. I'd like to add support for anything/everything at some point, but keeping the issue open doesn't help that. If anyone wants to get started, I'd love that.

**Closed by sergeyklay** 2017-06-22 06:24 UTC
Labels: Ubuntu
